### ISSUE TITLE
PCS login should last longer than 1 hour

### ISSUE THREAD

**Issue by dluc** [Azure/pcs-cli#201] opened 2017-10-31 18:53 UTC
# Type of issue 
- [ ] Bug
- [ ] New feature
- [x] Enhancement

# Description 
The auth token expires too soon, sometimes in the middle of a deployment. The token should last at least 24 hours, and/or give the user a choice for even a longer period if they'd like, e.g. in a dev environment.

Also, if the token is about to expire, the tool should refresh it automatically to avoid it expiring in the middle of a deployment.

**Comment by vitoc** [comment] 2017-11-23 10:31
This looks like a duplicate of #171

**Comment by ppathan** [comment] 2018-09-06 05:45
Will be fixed when moving to CIQS

**Closed by ppathan** 2018-09-06 05:45 UTC
Labels: GA, Triaged
