### ISSUE TITLE
Need to remove regions that not support specific VM, or other resouces

### ISSUE THREAD

**Issue by joyhui** [Azure/pcs-cli#129] opened 2017-09-19 05:29 UTC
# Type of issue

- [ ] Bug
- [x] New feature
- [ ] Improvement

# Description

I choose West US from command line, but it tells me SKU for that VM is not available after running around 5 mins. 

Since there is no remove resources command, I have to go to portal to delete them manually.

**Comment by ppathan** [comment] 2017-10-05 18:17
Closing as a dupe of #147

**Closed by ppathan** 2017-10-05 18:17 UTC
Labels: MVP, P2, Triaged
