### ISSUE TITLE
cli script hangs

### ISSUE THREAD

**Issue by JetstreamRoySprowl** [Azure/pcs-cli#414] opened 2018-11-08 01:31 UTC
# Type of issue 

- [x] Bug

# Description
On my main (and brand new) computer, when I run 
`pcs -t remotemonitoring -s basic -r dotnet`
the script accepts my solution name and my subscription choice, but it then hangs
indefinitely after it accepts the subscription. No further keystrokes are responded to at all. 
I have to close the command window to get rid of it.

I do not have this problem creating the same solution on one of my other machines (with a whole bunch
of other npm packaged installed).

I've included a file showing the session. It shows a fresh `npm install -g iot-solutions` output followed
by the problematic login/command sequence.
[pcs session.txt](https://github.com/Azure/pcs-cli/files/2559924/pcs.session.txt)

# Context and Environment
* Operating System: Windows 10 pro 64 Version 10.0.17134.345
* GitHub branch: N/A
* Node.js Runtime: v10.13.0 (64 bit)

**Comment by JetstreamRoySprowl** [comment] 2018-11-17 01:48
This hanging behavior continues in the recent 2.0.0 commit. I've discovered that the failure happens with nodejs version 10.13.0 but not with nodejs version 8.3.0

**Comment by ppathan** [comment] 2018-11-18 01:19
I have tried it with 10.13 node version and I'm able to run the command without issues. The latest released version for CLI is 1.0.13. Can you try again?

**Comment by JetstreamRoySprowl** [comment] 2018-11-19 01:03
I did try again; on my older box which was able to run successfully using the npm published iot-solutions, I was able to reproduce this failure by upgrading to node 10.13.0 with no other changes. That makes two machines to repro the problem.

**Comment by ppathan** [comment] 2018-11-19 19:59
Also reported by #431

**Comment by JetstreamRoySprowl** [comment] 2018-11-19 20:32
This has been closed, so I presume a solution exists. Can you point me to it? the dup you mentioned doesn't have the solution either, but it's also closed.

**Comment by ppathan** [comment] 2018-11-19 22:04
Not sure what you mean, this issue is still open. I closed the other issue.

**Comment by toddwhitehead** [comment] 2018-11-20 02:50
I get same issue with node 10.13.0

**Comment by sakimsft** [comment] 2018-11-20 16:15
The cause is identified and fix is on the way.

**Comment by elvinm** [comment] 2018-11-27 19:29
Yes this has been fixed here https://github.com/Azure/pcs-cli/pull/438 though we haven't published a newer version of the package yet. If you are building the packages locally (npm install & npm start & npm link) then you can just grab the latest code from master.

If not, please let me know and I'll find what our timeline is on getting an update pushed out.

**Comment by avneet723** [comment] 2018-11-28 19:23
Will be in the next release.

**Closed by avneet723** 2018-11-28 19:23 UTC
Labels: P1, Triaged, bug
