### ISSUE TITLE
stuck while running pcs command to deploy solution

### ISSUE THREAD

**Issue by akn9050** [Azure/pcs-cli#431] opened 2018-11-19 09:49 UTC
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
After running PCS command, provided solution name, after that selected subscription and press enter but after that nothing is happening.
![snag_13113cfc](https://user-images.githubusercontent.com/27498287/48698835-1a50cb80-ec0e-11e8-840d-50bc7a28bb59.png)
  
...

# Steps to reproduce 

1. [First step]
2. [Second step]
3. [and so on...]

# Expected behavior 
...

# Current behavior 
...

# Possible solution 
...

# Context and Environment
* Operating System: ...win 10
* GitHub branch: ...
https://github.com/Microsoft/MCW-IoT-for-business
https://github.com/solliancenet/LABVM
* Node.js Runtime: ...

**Comment by ppathan** [comment] 2018-11-19 19:59
Duplicate of #414 Closing this one.

**Closed by ppathan** 2018-11-19 19:59 UTC
Labels: duplicate
