### ISSUE TITLE
pcs basic deploy fails with InvalidTemplate code

### ISSUE THREAD

**Issue by ontracanoer** [Azure/pcs-cli#259] opened 2018-04-03 23:11 UTC
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
_Not sure if this is a bug, or just my lack of experience._

Following the instructions for How to use the CLI, the process always fails after pcs command with code: InvalidTemplate and message: Deployment template validation failed: 'The template parameters 'dockerTag' in the parameters file are not valid; they are not present in the original template and can therefore not be provided at deployment time.

# Steps to reproduce 

1. Open windows 10 command prompt
```
2. git clone --recursive https://github.com/Azure/azure-iot-pcs-remote-monitoring-dotnet.git
3. cd azure-iot-pcs-remote-monitoring-dotnet\cli
4. npm install
5. npm start
6. npm link
7. pcs login
8. pcs
```

# Expected behavior 
expected to see output.json file and information on a deployment for the entered solution name in the Azure portal.  The solution name appears as a resource group, but has no resources or deployments listed for it. 

# Current behavior 
...

# Possible solution 
...

# Context and Environment
* Operating System: Windows 10 x64 Enterprise
* GitHub branch: ...
* Node.js Runtime: v8.9.1

**Comment by ayyapureddy** [comment] 2018-04-11 09:29
Even I am facing exactly same issue on same environment. Node.js version is 8.9.4

**Comment by ppathan** [comment] 2018-04-12 16:53
The issue is fixed by this PR: https://github.com/Azure/pcs-cli/pull/260. It is merged in the https://github.com/Azure/pcs-cli repo but not in the top-level repo yet. It is best to use released version from npm `npm install -g iot-solutions`

**Closed by ppathan** 2018-04-12 16:53 UTC
